Increment 9 initial commit
PavelVGordeev/shorter pull request #4
Opened 2022-05-18 14:42 UTC by PavelVGordeev

2022-05-27 13:09 UTC, blattaria7 commented on internal/app/repo/repo.go
> +		userid += 1
принято писать ` userid++`

2022-05-27 13:10 UTC, blattaria7 commented on internal/app/storage/storage.go
> +	if perr, ok := err.(*pq.Error); ok && perr.Code == "23505" {
тут можно попробовать заюзать`errors.As` (для читаемости)

2022-05-27 13:12 UTC, blattaria7 commented on internal/app/repo/repo.go
> +	ctx, cancel := context.WithTimeout(ctx, 4*time.Second)
хорошо бы таймауты вынести в константы выше) и расписать что это за таймаут (вижу что ниже тоже самое, надо отразить в названии этот таймаут - один для пинга, второй для запросов)

2022-05-27 13:14 UTC, blattaria7 commented on internal/app/repo/repo.go
> +	err := newdb.Inspect()
здесь ошибка используется только для проверки, можно воспользоваться коротким объявлением:

```go
	if err := newdb.Inspect(); err != nil {
		return nil
	}
```

2022-05-27 13:19 UTC, blattaria7 commented on internal/app/storage/storage.go
> +func NewStorage(filepath string, dsn string) Storage {
в инициализации нужно возвращать структуру, а не интерфейс) 
у структуры должны быть методы, соответствующие интерфейсу. и уже уровень выше взаимодействует с этим интерфейсом 

почитай как работает утиная типизация в го)
[вот моя небольшая статейка] на эту тему (https://www.notion.so/e1118c9dc4a44a40aebdf21de5a41aea ) и небольшой [пример кода](https://github.com/blattaria7/go-template) с реализацией утиной типизации

2022-05-27 13:24 UTC, PavelVGordeev commented on internal/app/repo/repo.go
> +		userid += 1
Тут меня с питоном переклинило, что так написать нелья :)

2022-05-27 13:28 UTC, blattaria7 commented on internal/app/handlers/handlers.go
> +		su, uid, err := h.store.Store(r.Context(), uid, string(body))
su я бы переименовала более полно) так как не понятно, что это за переменная)
очень важно следить за читаемостью в коде - ведь большую часть времени разработчики именно читают код 😉

2022-05-27 13:29 UTC, blattaria7 commented on internal/app/storage/storage.go
> +	ms := NewMapStorage()
тут тоже можно переименовать в `mapStorage`

2022-05-27 13:30 UTC, blattaria7 commented on internal/app/storage/storage.go
> +	ps := &FileStorage{
`fileStorage`

2022-05-27 13:31 UTC, blattaria7 commented on internal/app/storage/storage_test.go
> +	if got, _, _ := s.Store(context.TODO(), 0, url); got != want {
нельзя игнорировать ошибки - это антипаттерн. надо добавить `assert.NoError(err)`

2022-05-27 13:31 UTC, blattaria7 commented on internal/app/storage/storage_test.go
> +	if got, _, _ := s.Store(context.TODO(), 0, url); got != want {
дальше тоже нужно это сделать

2022-05-27 13:33 UTC, blattaria7 requested changes
Отличная работа! Мне очень нравится то, как выполнено задание. Но есть несколько логических ошибок (реализация утиной типизации и игнорирование ошибок), которые нужно поправить. Буду ждать доработки =)

2022-05-31 09:28 UTC, blattaria7 approved these changes
Все отлично, ставлю аппрув =)

2022-05-31 09:36 UTC, merged